/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1

// OCIImageApplyConfiguration represents a declarative configuration of the OCIImage type for use
// with apply.
type OCIImageApplyConfiguration struct {
	// ref is the OCI Image reference for the bundle. A bundle installed this way is reconciled only
	// when a clusterextension is first created or the ref has been updated.
	Ref *string `json:"ref,omitempty"`
}

// OCIImageApplyConfiguration constructs a declarative configuration of the OCIImage type for use with
// apply.
func OCIImage() *OCIImageApplyConfiguration {
	return &OCIImageApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *OCIImageApplyConfiguration) WithRef(value string) *OCIImageApplyConfiguration {
	b.Ref = &value
	return b
}
